theme: jekyll-theme-cayman
title: Miles C. Coleman

## Communication Instructor and Researcher

`{digital} rhetoric` - `science, technology, and medicine` - `communication ethics`

### Projects 

-[feels_bot](http://milesccoleman.com/feels_bot/) 
