theme: jekyll-theme-cayman
title: Miles C. Coleman
description: {digital} rhetoric - science, technology, and medicine - communication ethics
## Communication Instructor and Researcher



### Projects 

-[feels_bot](http://milesccoleman.com/feels_bot/) 
